services:
  jupyter:
    build: .
    container_name: uwin-jupyter

    ports:
      - "8888:8888"

    volumes:
      - .:/home/jovyan/project
    
    environment:
      JUPYTER_TOKEN: ${JUPYTER_TOKEN:-changeme}
      UWIN_DATA_ROOT: /home/jovyan/project/data
      UWIN_SITE: GWD_10_160 # Default
      PYTHONPATH: /home/jovyan/project/src
 
    working_dir: /home/jovyan/project/notebook
    restart: unless-stopped